pulumi/templates

templates/aws-go/Pulumi.yaml, templates/aws-javascript/Pulumi.yaml, templates/aws-python/Pulumi.yaml, templates/aws-typescript/Pulumi.yaml, templates/go/Pulumi.yaml, templates/hello-aws-javascript/Pulumi.yaml, templates/javascript/Pulumi.yaml, templates/python/Pulumi.yaml, templates/typescript/Pulumi.yaml
This adds a top-level `template` key to each template's `Pulumi.yaml` (what we'd previously talked about calling `quickstart`).
An optional `quickstart` key under `template` is supported to specify text to print to `stdout` after project creation (though, none of the templates here currently use it).
Note that the existing `.pulumi.template.yaml` files will remain for now for versions of the CLI still in use (until we can phase it out). The updated template implementation ignores/skips this file if it is present.
=> Add template section to Pulumi.yaml files

aws-javascript/.gitignore, aws-python/.gitignore, aws-typescript/.gitignore, javascript/.gitignore, python/.gitignore, typescript/.gitignore
This is a holdover from a long while back where Pulumi would keep
certain bookeeping data in a directory called .pulumi at the root of
your application.
We no longer do this, so we can remove these directives.
=> Remove the .pulumi folder from .gitignore in templates

kubernetes-typescript/.gitignore, kubernetes-typescript/Pulumi.yaml, kubernetes-typescript/index.ts, kubernetes-typescript/package.json, kubernetes-typescript/tsconfig.json
I removed the `// Parameters` comments, kept `name` and `image` `const`s, and moved `replicas` inline.
~~Note: Matt and I are still playing around with whether we want to keep the `tsconfig.json` in the templates or not. If we decide we don't want it, I'll remove it in a follow-up PR.~~ We're going to keep the `tsconfig.json` for now.
---
If you want to try it out before this PR is merged:
```bash
pulumi new https://github.com/pulumi/templates/tree/justin/k8s/kubernetes-typescript
```
After it's merged it will be:
```bash
pulumi new kubernetes-typescript
```
=> Add minimal Kubernetes template

kubernetes-javascript/index.js, kubernetes-typescript/index.ts
This change exports the resulting Kubernetes deployment name
from the templates, making it easier to tool. E.g.
$ pulumi new kubernetes-typescript
...
$ kubectl get deployment $(pulumi stack output name)
=> Export the Kubernetes deployment name

aws-javascript/package.json, aws-typescript/package.json, azure-javascript/package.json, azure-typescript/package.json, gcp-javascript/package.json, gcp-typescript/package.json, javascript/package.json, kubernetes-javascript/package.json, kubernetes-typescript/package.json, openstack-javascript/package.json, openstack-typescript/package.json, typescript/package.json
We've moved away from using the ${PROJECT} and ${DESCRIPTION} replacement strings in Pulumi.yaml and package.json, primarily so that `pulumi new <url>` and `pulumi up <url>` can be used with examples that don't use these replacement strings (allowing such examples to be usable/buildable on their own without any templating).
Instead of doing a search/replace of these replacement strings, v0.15.2 of the CLI now overwrites any existing `name` and `description` values in Pulumi.yaml and saves the file, and doesn't do anything to update/save the `name` specified in package.json. The replacement strings can be used, but they are no longer required with this version of the CLI.
However, v0.15.0 of the CLI only does a search/replace, so we must keep ${PROJECT} and ${DESCRIPTION} in Pulumi.yaml in …
=> Stop replacing the project name in package.json

hello-aws-javascript/package.json
Having `pulumi new` generate a project that just installs daily builds
is likely to lead to a bad experience.
Move to "latest" like the other templates, which picks up the most
recently released version.
=> Don't use "dev" tags in templates

aws-go/main.go
`BucketDomainName` is a function, so it should be called 👌 
Before:
```
▲ (matheus-vm) infra [add/pulumi] pulumi preview
Previewing update (redacted):
Type                 Name                   Plan       Info
+   pulumi:pulumi:Stack  redacted  create     1 error; 2 messages
+   └─ aws:s3:Bucket     my-bucket              create
Diagnostics:
pulumi:pulumi:Stack (redacted):
error: program failed: 1 error occurred:
* marshaling outputs: awaiting input property bucketName: unrecognized input property type: 0xa00d00 (func() *pulumi.StringOutput)
error: an unhandled error occurred: program exited with non-zero exit code: 1
Permalink: redacted
error: an error occurred while advancing the preview
▲ (matheus-vm) infra [add/pulumi]
```
After:
```
▲ (matheus-vm) infra [add/pulumi] pulumi preview …
```
=> Add missing function call to `aws-go`

aws-go/main.go, aws-javascript/index.js, aws-python/__main__.py, aws-typescript/index.ts
The domain name is almost never needed.
The name of the bucket which is used for `s3://` paths (as well as in the domain name) is the more generally useful and is available as the `id` property.
=> Export the ID of the bucket instead of the domain name

aws-javascript/package.json, aws-typescript/package.json, azure-javascript/package.json, azure-typescript/package.json, digitalocean-javascript/package.json, digitalocean-typescript/package.json, gcp-javascript/package.json, gcp-typescript/package.json, hello-aws-javascript/package.json, javascript/package.json, kubernetes-javascript/package.json, kubernetes-typescript/package.json, linode-javascript/package.json, linode-typescript/package.json, openstack-javascript/package.json, openstack-typescript/package.json, packet-javascript/package.json, packet-typescript/package.json, typescript/package.json
Until we have finalized the preparations for `1.0.0-beta.1` across providers, we need to ensure that we fix this so that users don't get a mix of Pulumi package version.
=> Pin NPM dependencies to `0.x.y`

alicloud-visualbasic/${PROJECT}.vbproj, aws-visualbasic/${PROJECT}.vbproj, azure-visualbasic/${PROJECT}.vbproj, gcp-visualbasic/${PROJECT}.vbproj, visualbasic/${PROJECT}.vbproj
Visual Basic assumes the project name to be the root namespace by default. With dynamic project names, it can be set to something like `test-name` which is not a valid namespace.
This leads to a broken project ([example](https://travis-ci.com/pulumi/templates/builds/148539544#L1481)).
Blanking out the root namespace explicitly should help avoid the situation. I tested and the project compiles and runs.
=> Blank root namespaces for VB

azure-go/main.go
The example doesn't currently compile or run. This fixes that. Contributes to https://github.com/pulumi/docs/issues/2311
=> fix azure example

tests/go.mod, tests/go.sum, tests/template_test.go
The integration test package by default uses Pipenv to manage virtual environments for Python test projects. As of Pulumi 2.4.0, `pulumi new` will automatically create and manage a virtual environment itself, which is causing these template tests to fail because Pulumi is trying to manage a virtual environment created in the context of a Pipenv virtual environment. To address, we need to set the new `UseAutomaticVirtualEnv` test option, which prevents the use of Pipenv.
Follow-up from https://github.com/pulumi/pulumi/pull/4775
=> Fix Python template tests

alicloud-go/go.mod, aws-go/go.mod, azure-go/go.mod, azure-nextgen-go/go.mod, digitalocean-go/go.mod, gcp-go/go.mod, go/go.mod, kubernetes-go/go.mod, linode-go/go.mod, openstack-go/go.mod, packet-go/go.mod
just do the simple thing to make sure new users are getting the latest build (for now)
broader issue tracked here: https://github.com/pulumi/templates/issues/114
=> bump sdk version for go templates

.github/workflows/run-templates-command.yml, tests/template_test.go
If we are changing the templates in a PR, then we should pass
the ref to the template checkout otherwise we are running tests
from the main line not the PR itself
=> Run the templates from the PR source if exists

azure-csharp/MyStack.cs, azure-fsharp/Program.fs, azure-python/__main__.py
After making Azure-native the default, some of the current templates still have references to the deprecated `latest` namespace/module, so this updates the templates to use the top-level namespace/module.
=> Remove deprecated 'latest' from Azure native templates

.github/workflows/ci.yml, .github/workflows/cron.yml
Ubuntu latest was failing on:
- Run Template Tests Against Latest CLI + Dev CLI
- Run Template Tests on Push or as Part of a Release
With errors of 
```
/tmp/test-env018029435/test-env018029435.fsproj : error NU1102: Unable to find package Pulumi with version (>= 3.11.0)
/tmp/test-env018029435/test-env018029435.fsproj : error NU1102:   - Found 1532 version(s) in nuget.org [ Nearest version: 3.11.0-alpha.1629906058 ]
```
Performing a clean before run has now produced the following success runs:
- https://github.com/pulumi/templates/runs/3479794426?check_suite_focus=true
- https://github.com/pulumi/templates/runs/3478973737?check_suite_focus=true
=> fix for failed builds fetching nuget packages

alicloud-typescript/package.json, aws-typescript/package.json, azure-classic-typescript/package.json, azure-typescript/package.json, digitalocean-typescript/package.json, equinix-metal-typescript/package.json, gcp-typescript/package.json, google-native-typescript/package.json, kubernetes-typescript/package.json, linode-typescript/package.json, openstack-typescript/package.json, typescript/package.json
We probably want to use Node 14, as it's recommended for most applications. Node v10 is EOL.
=> chore: bump from node v10 to v14

kubernetes-go/go.mod
Go 1.16 adds embed (used by the SDK). This bumps from 1.14 -> 1.16
Currently, on a bone stock Debian system, when you run `pulumi new kubernetes-go` you get
```
indrora@debkube:~/quickstart$ pulumi new kubernetes-go
This command will walk you through creating a new Pulumi project.
Enter a value or leave blank to accept the (default), and press <ENTER>.
Press ^C at any time to quit.
project name: quickstart
Sorry, 'quickstart' is not a valid project name. A project with this name already exists.
project name: quickstart
project description: (A minimal Kubernetes Go Pulumi program)
Created project 'quickstart'
Please enter your desired stack name.
To create a stack in an organization, use the format <org-name>/<stack-name> (e.g. `acmecorp/dev`).
stack name: (dev)
Created stack 'dev' …
```
=> Push kubernetes-go golang minimum to 1.16

alicloud-csharp/${PROJECT}.csproj, alicloud-fsharp/${PROJECT}.fsproj, alicloud-visualbasic/${PROJECT}.vbproj, aws-csharp/${PROJECT}.csproj, aws-fsharp/${PROJECT}.fsproj, aws-visualbasic/${PROJECT}.vbproj, azure-classic-csharp/${PROJECT}.csproj, azure-classic-fsharp/${PROJECT}.fsproj, azure-classic-visualbasic/${PROJECT}.vbproj, azure-csharp/${PROJECT}.csproj, azure-fsharp/${PROJECT}.fsproj, fsharp/${PROJECT}.fsproj, gcp-csharp/${PROJECT}.csproj, gcp-fsharp/${PROJECT}.fsproj, gcp-visualbasic/${PROJECT}.vbproj, google-native-csharp/${PROJECT}.csproj, kubernetes-csharp/${PROJECT}.csproj, kubernetes-fsharp/${PROJECT}.fsproj
This change ensures the .NET projects always get the latest `Pulumi` package. Otherwise, the `Pulumi` package is a transitive dependency that is resolved to the **lowest** version that matches the requirements of the package that depends on it.
Fixes #230
=> Ensure .NET projects always get the latest Pulumi package

gcp-typescript/package.json
in oder to use the lates version of the GCP Pulumi provider the package.json is updated to use the version ^6.0.0
=> Upate @pulumi/gcp version

azure-yaml/Pulumi.yaml, azure-yaml/Pulumi.yaml.append
Otherwise the default program fails with
> Code="AccountNameInvalid" Message="storageAccount6289248d is not a valid storage account name. Storage account name must be between 3 and 24 characters in length and use numbers and lower-case letters only."
=> Shorten storage account name in Azure YAML

azure-java/Pulumi.yaml
Without this, we get the following first-run experience:
```
Diagnostics:
azure-native:resources:ResourceGroup (resourceGroup):
error: azure-native:resources:ResourceGroup resource 'resourceGroup' has a problem: missing required property 'location'. Either set it explicitly or configure it with 'pulumi config set azure-native:location <value>'.
```
=> Add `location` to `azure-java` template config

gcp-java/Pulumi.yaml
Without this, we get the following first-run experience:
```
Diagnostics:
pulumi:pulumi:Stack (quickstart-dev):
error: update failed
gcp:storage:Bucket (my-bucket):
error: 1 error occurred:
* project: required field is not set
```
Looks like all other `gcp-*` templates have this as well.
=> Add `project` to `gcp-java` template config

aws-yaml/Pulumi.yaml, gcp-yaml/Pulumi.yaml.append
Going through the recent additions to the getting-started guides, I noticed we use the resource name `bucket` in these two templates, but we use `my-bucket` in all of the others. Since we have shared code in our guides that refers to this bucket as `my-bucket`, it'd be nice to update it here, both for consistency and to keep from having to special-case a bunch of the prose in the guides. Thank you!
=> Change the name of the bucket resource to my-bucket

alicloud-javascript/Pulumi.yaml, auth0-javascript/Pulumi.yaml, aws-javascript/Pulumi.yaml, aws-native-javascript/Pulumi.yaml, azure-classic-javascript/Pulumi.yaml, azure-javascript/Pulumi.yaml, civo-javascript/Pulumi.yaml, digitalocean-javascript/Pulumi.yaml, equinix-metal-javascript/Pulumi.yaml, gcp-javascript/Pulumi.yaml, github-javascript/Pulumi.yaml, hello-aws-javascript/Pulumi.yaml, javascript/Pulumi.yaml, kubernetes-javascript/Pulumi.yaml, linode-javascript/Pulumi.yaml, oci-javascript/Pulumi.yaml, openstack-javascript/Pulumi.yaml
Projects that do not use TypeScript still pay some TypeScript-related overheads inside Pulumi. One overhead is `import "typescript"` in nodejs costing 300ms. `pulumi-language-nodejs` currently thinks that every project is a TypeScript project, it does not autodetect; unless it is told otherwise using this option. While we could consider auto-detection, I am afraid it might break some projects out there; so the safer path in this PR is to opt out of TypeScript explicitly for all the JavaScript templates so the new projects take advantage of the related optimizations.
=> Opt out of TypeScript in JavaScript templates

kubernetes-java/pom.xml
Last known working version 3.19.1
This fixes `pulumi new java-kubernetes` for now.
Once https://github.com/pulumi/pulumi-java/issues/774 fix lands in a new version of Java Kubernetes SDK we might want to go back to a floating reference in the template.
=> Withhold broken kubernetes provider update

tests/performance_test.go, tests/template_test.go
Do not use Quick: True when performance testing, as it skews the benchmarks. 
https://github.com/pulumi/home/issues/1498
Test run: https://github.com/pulumi/templates/runs/7954302544?check_suite_focus=true
=> Consistent test options

tests/template_test.go
https://github.com/pulumi/templates/actions/workflows/cron.yml seeing quite a few timeout related failures. It's not great we have templates timing out in 30min but some of it seems to be an artifact of the CI environment (cannot repro locally). The higher timeout would let us focus on the few tests that do get stuck.
=> More generous timeouts

aws-native-fsharp/Program.fs
The name was so common it generated hash collisions failing tests https://github.com/pulumi/templates/runs/8032164262?check_suite_focus=true#step:19:406 even though Pulumi disambiguates resources randomly.
=> Use a more unique bucket name

.github/workflows/ci.yml, .github/workflows/cron.yml, .github/workflows/performance_metrics_cron.yml, .github/workflows/run-templates-command.yml
I've noticed that Go-based template tests started failing. The underlying issue is https://github.com/pulumi/pulumi/issues/10864 as Pulumi dropped 1.17 support it seems in a recent release.
According to https://endoflife.date/go though support for 1.17 ended 1 months ago, so moving the tests to Go 1.18 is reasonable as it will represent a broader set of our users. We could test more versions but likely not enough CI capacity yet.
CC @AaronFriel
=> Use go 1.18.x toolchain

.github/workflows/ci.yml, .github/workflows/cron.yml, .github/workflows/run-templates-command.yml, tests/internal/testutils/config.go, tests/internal/testutils/environments.go
Likely the CI out of disk space issues occur because we don't clean up the temp folders. https://github.com/pulumi/pulumi/issues/9437 seems to be closed now. Should it be safe to re-enable cleaning the temp folders on CI?
Fixes #370 also
=> Always cleanup the temp dirs

.github/workflows/ci.yml, .github/workflows/run-templates-command.yml
Adjusts a couple of workflows to skip container-related template tests on Windows and Mac.
Fixes #386.
=> Skip container-* tests on Windows and Mac

azure-classic-csharp/Pulumi.yaml, azure-classic-fsharp/Pulumi.yaml, azure-classic-go/Pulumi.yaml, azure-classic-go/main.go, azure-classic-javascript/Pulumi.yaml, azure-classic-python/Pulumi.yaml, azure-classic-typescript/Pulumi.yaml, azure-classic-visualbasic/Pulumi.yaml, azure-classic-yaml/Pulumi.yaml, azure-csharp/Pulumi.yaml, azure-fsharp/Pulumi.yaml, azure-go/Pulumi.yaml, azure-java/Pulumi.yaml, azure-javascript/Pulumi.yaml, azure-python/Pulumi.yaml, azure-typescript/Pulumi.yaml, azure-yaml/Pulumi.yaml
WestUS has capacity constraints and is not recommended in the Azure Portal anymore.
=> Change default Azure region to better supported WestUS2

.github/workflows/run-templates-command.yml
The repository for one of the tools we use in CI has moved to another GitHub organization ([announcement here](https://github.com/GoTestTools/gotestfmt/discussions/46)). This change fixes things up.
=> Update the gotestfmt organization

README.md, metadata/groups/container-service-aws.yaml, metadata/groups/serverless-application-aws.yaml
Adds a bit to the README about what to do when you create a new architecture template, and fixes a couple of typos in existing metadata files.
=> Add template-metadata docs, fix a couple of metadata bugs

metadata/groups/kubernetes-gcp.yaml
This PR adds a metadata/groups file for templates for Kubernetes on Google Cloud.
=> Add metadata for Kubernetes on Google Cloud

container-azure-typescript/app/package.json, kubernetes-aws-typescript/package.json, kubernetes-azure-typescript/package.json, kubernetes-gcp-typescript/package.json, serverless-azure-typescript/app/package.json, serverless-azure-typescript/package.json, serverless-gcp-typescript/app/package.json, serverless-gcp-typescript/package.json, static-website-aws-typescript/package.json, static-website-azure-typescript/package.json, static-website-gcp-typescript/package.json
Happened to notice these need to be templated also. (I'll also follow up with an issue to add some linting for this sort of thing!)
=> Fix non-templated TypeScript project names

kubernetes-aws-python/__main__.py
There is a missing comma when reading the `eksNodeInstanceType` config value causing it to always evaluate to `None` since the key is getting implicitly concatenated to `eksNodeInstanceTypet3.medium`, which doesn't exist in the configuration. Adding the comma will cause the value to read in from the configuration.
=> Add comma when reading eksNodeInstanceType config value

container-azure-go/go.mod, container-gcp-go/go.mod, kubernetes-aws-go/go.mod, kubernetes-azure-go/go.mod, kubernetes-gcp-go/go.mod, serverless-aws-go/go.mod, serverless-azure-go/go.mod, serverless-gcp-go/app/go.mod, serverless-gcp-go/go.mod, static-website-aws-go/go.mod, static-website-azure-go/go.mod, static-website-gcp-go/go.mod
These should be `${PROJECT}` as well, like the others. Includes a similar tweak to the module name of the GCP serverless function template's module name, which is slightly different because of GCP naming restrictions.
=> Fix Go module names

metadata/groups/container-service-gcp.yaml
I overlooked this file when I submitted the templates.
=> Add `container-gcp-*` template metadata

static-website-azure-typescript/index.ts
This is incorrect -- it should be the URL emitted by the storage account, as in the other languages of this template. (The endpoint actually isn't available over HTTP.) [Internal convo here](https://pulumi.slack.com/archives/C043485KTDW/p1667275877490969).
=> Fix exported origin URL

tests/metadata/metadata.test.js
The `metadata.json` file has an `architectures` section that lists the templates that belong to each architecture. Because we manage these lists by hand (by appending template names as strings to each template group), it's technically possible to list a template that doesn't actually exist, which could break consumers of this file (e.g., the Service) that rely on it for creating new projects. So this change adds a couple of tests to enure every template referenced in `metadata.json` also exists in the repository.
=> Add a test that ensures arch templates also exist

container-azure-go/app/Dockerfile, container-gcp-go/app/Dockerfile
The current template fails on M1 Macs due to the architecture differences. This change sidesteps the issue with env variables in Go with docker.Image.
=> Fix Azure/Google Cloud Go-Container templates

metadata/architectures.yaml, metadata/dist/metadata.json, tests/metadata/metadata.test.js
To align with the changes in https://github.com/pulumi/pulumi-hugo/pull/2183, this change updates the name of the Kubernetes architecture templates to "Kubernetes Cluster", and also adds a test for the Kubernetes Application templates.
=> Rename Kubernetes architecture to Kubernetes Cluster

metadata/dist/metadata.json, metadata/groups/container-service-aws.yaml, metadata/groups/container-service-azure.yaml, metadata/groups/container-service-gcp.yaml, metadata/groups/helm-kubernetes.yaml, metadata/groups/kubernetes-aws.yaml, metadata/groups/kubernetes-azure.yaml, metadata/groups/kubernetes-gcp.yaml, metadata/groups/serverless-application-aws.yaml, metadata/groups/serverless-application-azure.yaml, metadata/groups/serverless-application-gcp.yaml, metadata/groups/static-website-aws.yaml, metadata/groups/static-website-azure.yaml, metadata/groups/static-website-gcp.yaml, metadata/groups/virtual-machine-aws.yaml, metadata/groups/virtual-machine-azure.yaml, metadata/groups/virtual-machine-gcp.yaml, metadata/groups/webapp-kubernetes.yaml
These group names are more verbose than what's needed in the Service UI, so this change strips out the cloud names to make them a bit tidier. Additional context [in this thread](https://pulumi.slack.com/archives/C0289AASSG4/p1667500236565769).
This change will have no user-facing impact until the accompanying Service change (https://github.com/pulumi/pulumi-service/pull/11034) is merged.
Part of https://github.com/pulumi/pulumi-service/issues/11031.
=> Drop cloud references from template group names

kubernetes-azure-csharp/Program.cs
Uncomment the reference to subnet when creating the AKS node pool. Otherwise, the created AKS cluster does not use the virtual network and subnet created earlier in the template.
Fixes #443
=> Fix commented reference to subnet

.github/workflows/performance_metrics_cron.yml
https://github.com/pulumi/templates/actions/runs/3475152250/jobs/5809065821 an example of running out of disk space. Skipping these for now should speed up the job and save disk space.
=> Skip benchmarks to save disk space on container

container-aws-yaml/Pulumi.yaml, container-aws-yaml/Pulumi.yaml.append, helm-kubernetes-yaml/Pulumi.yaml, helm-kubernetes-yaml/Pulumi.yaml.append, kubernetes-aws-yaml/Pulumi.yaml, kubernetes-aws-yaml/Pulumi.yaml.append, kubernetes-azure-yaml/Pulumi.yaml, kubernetes-azure-yaml/Pulumi.yaml.append, kubernetes-gcp-yaml/Pulumi.yaml, kubernetes-gcp-yaml/Pulumi.yaml.append, serverless-azure-yaml/Pulumi.yaml, serverless-azure-yaml/Pulumi.yaml.append, serverless-gcp-yaml/Pulumi.yaml, serverless-gcp-yaml/Pulumi.yaml.append, static-website-aws-yaml/Pulumi.yaml, static-website-aws-yaml/Pulumi.yaml.append, static-website-azure-yaml/Pulumi.yaml, static-website-azure-yaml/Pulumi.yaml.append, static-website-gcp-yaml/Pulumi.yaml, static-website-gcp-yaml/Pulumi.yaml.append, vm-aws-yaml/Pulumi.yaml, vm-azure-yaml/Pulumi.yaml, vm-azure-yaml/Pulumi.yaml.append, vm-gcp-yaml/Pulumi.yaml, vm-gcp-yaml/Pulumi.yaml.append, webapp-kubernetes-yaml/Pulumi.yaml, webapp-kubernetes-yaml/Pulumi.yaml.append, yaml/Pulumi.yaml, yaml/Pulumi.yaml.append
pulumi-yaml `configuration` is being deprecated in favor of the project-level `config` block 
Fixes #453
=> Update examples to use config instead of configuration

container-aws-yaml/Pulumi.yaml, container-aws-yaml/Pulumi.yaml.append, helm-kubernetes-yaml/Pulumi.yaml, helm-kubernetes-yaml/Pulumi.yaml.append, kubernetes-aws-yaml/Pulumi.yaml, kubernetes-aws-yaml/Pulumi.yaml.append, kubernetes-azure-yaml/Pulumi.yaml, kubernetes-azure-yaml/Pulumi.yaml.append, kubernetes-gcp-yaml/Pulumi.yaml, kubernetes-gcp-yaml/Pulumi.yaml.append, serverless-azure-yaml/Pulumi.yaml, serverless-azure-yaml/Pulumi.yaml.append, serverless-gcp-yaml/Pulumi.yaml, serverless-gcp-yaml/Pulumi.yaml.append, static-website-aws-yaml/Pulumi.yaml, static-website-aws-yaml/Pulumi.yaml.append, static-website-azure-yaml/Pulumi.yaml, static-website-azure-yaml/Pulumi.yaml.append, static-website-gcp-yaml/Pulumi.yaml, static-website-gcp-yaml/Pulumi.yaml.append, vm-aws-yaml/Pulumi.yaml, vm-azure-yaml/Pulumi.yaml, vm-azure-yaml/Pulumi.yaml.append, vm-gcp-yaml/Pulumi.yaml, vm-gcp-yaml/Pulumi.yaml.append, webapp-kubernetes-yaml/Pulumi.yaml, webapp-kubernetes-yaml/Pulumi.yaml.append, yaml/Pulumi.yaml, yaml/Pulumi.yaml.append
Reverts pulumi/templates#454
Test failures in `pulumi/pulumi` (https://github.com/pulumi/pulumi/actions/runs/3525688587/jobs/5912834569#step:36:112) likely due to change from `configuration` to `config` key in YAML templates.
Fixes https://github.com/pulumi/pulumi/issues/11433
=> Revert "Update examples to use config instead of configuration"

.gitignore, container-azure-csharp/${PROJECT}.csproj, container-gcp-csharp/${PROJECT}.csproj, helm-kubernetes-csharp/${PROJECT}.csproj, kubernetes-gcp-csharp/${PROJECT}.csproj, serverless-aws-csharp/${PROJECT}.csproj, serverless-azure-csharp/${PROJECT}.csproj, serverless-gcp-csharp/${PROJECT}.csproj, static-website-aws-csharp/${PROJECT}.csproj, static-website-azure-csharp/${PROJECT}.csproj, static-website-gcp-csharp/${PROJECT}.csproj, vm-aws-csharp/${PROJECT}.csproj, vm-azure-csharp/${PROJECT}.csproj, webapp-kubernetes-csharp/${PROJECT}.csproj
Allows programs to pick up minor and patch versions of Pulumi dependencies. (One of these templates, `serverless-aws-csharp`, is currently failing  because it's pinned to `Aws = 5.13.0`, but `AwsApiGateway` is trying to upgrade it to `>= 5.21.1`.)
```
...
my-serverless-app.csproj : error NU1605: Detected package downgrade: Pulumi.Aws from 5.21.1 to 5.13.0. Reference the package directly from the project to select a different version.
```
Fixes #469.
=> Unpin .NET dependencies

azure-go/go.mod, azure-go/main.go, container-azure-go/go.mod, container-azure-go/main.go, kubernetes-azure-go/go.mod, kubernetes-azure-go/main.go, serverless-azure-go/go.mod, serverless-azure-go/main.go, static-website-azure-go/go.mod, static-website-azure-go/main.go, vm-azure-go/go.mod, vm-azure-go/main.go
All the `// indirect` changes in go.mod are from `go mod tidy`.
Tested by replacing `${PROJECT}` in each template, then running `pulumi up` and observing that it gets to the config validation stage.
`grep -r github.com/pulumi/pulumi-azure-native/sdk/go` has no results now in the repo.
- Migrate azure-go to the split Go SDK
- Migrate container-azure-go to the split Go SDK
- Migrate kubernetes-azure-go to the split Go SDK
- Migrate serverless-azure-go to the split Go SDK
- Migrate static-website-azure-go to the split Go SDK
- Migrate vm-azure-go to the split Go SDK
fixes pulumi/pulumi-azure-native#2058
=> Migrate azure-native templates to new Go SDK

kubernetes-gcp-yaml/Pulumi.yaml, kubernetes-gcp-yaml/Pulumi.yaml.append
This PR fixes issues with the YAML template for Kubernetes on GCP, which was affected by the issue described in #477. No other templates were identified as being affected by #477.
This PR fixes #477.
=> Fix YAML template for Kubernetes on GCP

serverless-aws-csharp/${PROJECT}.csproj, serverless-aws-go/go.mod, serverless-aws-python/requirements.txt, serverless-aws-typescript/package.json, serverless-azure-csharp/${PROJECT}.csproj, serverless-azure-go/go.mod, serverless-azure-python/requirements.txt, serverless-azure-typescript/package.json, serverless-gcp-csharp/${PROJECT}.csproj, serverless-gcp-go/go.mod, serverless-gcp-python/requirements.txt, serverless-gcp-typescript/package.json, static-website-aws-csharp/${PROJECT}.csproj, static-website-aws-go/go.mod, static-website-aws-python/requirements.txt, static-website-aws-typescript/package.json, static-website-azure-csharp/${PROJECT}.csproj, static-website-azure-go/go.mod, static-website-azure-python/requirements.txt, static-website-azure-typescript/package.json, static-website-gcp-csharp/${PROJECT}.csproj, static-website-gcp-go/go.mod, static-website-gcp-python/requirements.txt, static-website-gcp-typescript/package.json
Upgrades dependencies on the `serverless-*` and `static-website-*` templates. 
I tested all of these manually as I went through them, so there shouldn't be any issues, but a few things to note:
* I noticed the API Gateway package was pinned to an older version of `pulumi-aws` (causing templates to pull down multiple versions of it), so I submitted a PR to fix that here: https://github.com/pulumi/pulumi-aws-apigateway/pull/70
* With these updates, the `serverless-azure-go` template emits a deprecation notice that I haven't tracked down yet but that appears to have something to do with the building of the packaged Go app. Doesn't interfere with deployment at all; is just a bit noisy. I'll see if I can figure out where it's coming from and address if possible in a follow-up.
* A new GCP …
=> Bump deps for static-website and serverless templates

container-gcp-typescript/index.ts
Locally on my mac m1 (arm) I had issue on gcp running the image:
> The user-provided container failed to start and listen on the port defined provided by the PORT=8080 environment variable. Logs for this revision might contain more information.
```
Diagnostics:
gcp:cloudrun:Service (service):
error: 1 error occurred:
* updating urn:pulumi:dev::pulumi-test01::gcp:cloudrun/service:Service::service: 1 error occurred:
* resource is in failed state "Ready:False", message: Revision 'service-XXXXXXX-XXXXX' is not ready and cannot serve traffic. The user-provided container failed to start and listen on the port defined provided by the PORT=8080 environment variable. Logs for this revision might contain more information.
```
Reading at [the …
=> fix(arm): default to linux/amd64

.github/workflows/ci.yml, .github/workflows/cron.yml, .github/workflows/run-templates-command.yml, generator/mod-templates/github-template.txt, github-go/go.mod, tests/template_test.go
As a follow-up to https://github.com/pulumi/devrel-team/issues/464, this change skips running full updates for all templates, relying instead on successful previews, and adds `vm-azure-yaml` and `kubernetes-azure-yaml` to the list of skipped tests.
Doesn't represent the ideal state for sure, but given the state we're in now, we think this is an acceptable trade-off to get back to reliably passing while we explore alternative ways to run full deployments for some or all templates.
Note that this change also skips testing `github-go` (temporarily) due to https://github.com/pulumi/templates/issues/481. I'll remove it from the list once that issue's fixed.
Fixes https://github.com/pulumi/devrel-team/issues/487.
=> Skip updates, {vm,kubernetes}-azure-yaml

aws-go/go.mod, azure-classic-go/go.mod, azure-go/go.mod, civo-go/go.mod, equinix-metal-go/go.mod, equinix-metal-go/main.go, gcp-go/go.mod, generator/generate-go-mod.sh, generator/mod-templates/equinix-metal-template.txt, github-go/go.mod
Running this script without a `GITHUB_TOKEN` [occasionally yields `null` values in `go.mod` files](https://github.com/pulumi/templates/pull/493) because of GitHub rate limiting. This change adds the ambient `GITHUB_TOKEN` to `curl` request headers and re-runs the script to regenerate updated values.  
Also "downgrades" `github-go` to `v4` while we sort out what's going on with #481.
=> Use GITHUB_TOKEN in curl requests, run generate-go-mod.sh

.github/workflows/cron.yml
This change temporarily removes testing of the "dev" CLI while the linked issue is worked out.
Fixes https://github.com/pulumi/templates/issues/388.
=> Temporarily comment pulumi-version: dev CLI tests

.github/workflows/run-templates-command.yml, fsharp/${PROJECT}.fsproj, fsharp/Program.fs, tests/internal/testutils/templates.go
Our PR tests use an environment variable, `PULUMI_TEMPLATE_LOCATION`, to pass the path of the checked-out branch to `pulumi new` to ensure that the tests run against the content of the PR. This environment variable, however, hasn't been getting set for some time, so the tests have actually been running against the templates in pulumi/templates@master, using  the default behavior of `pulumi new` (which clones over https). This change fixes that.
Interestingly, this change also seems to have surfaced new failures on Windows; specifically, all of the `fsharp` templates are now failing on the Windows runners, and a couple of `visualbasic` ones are now, too. This appears to have something to do with a UTF-8 byte-order mark that's apparently set by Visual Studio on Windows, but removing those …
=> Fix environment-variable reference

.github/workflows/ci.yml
Updates the `push` tests to run against the local checkout also (as we do for PRs, as of https://github.com/pulumi/templates/pull/500). Should make the README badge go green. 🤞 
Fixes https://github.com/pulumi/templates/issues/510.
=> Run `push` jobs against local checkout as well

.github/workflows/build-metadata.yml, .github/workflows/ci.yml, .github/workflows/cron.yml, .github/workflows/performance_metrics_cron.yml, .github/workflows/run-templates-command.yml, .github/workflows/test-metadata.yml
We've accumulated a number of warnings in our actions results:
To address these warnings, this change upgrades everything that can be upgraded and removes the one step we have that uses `set-output`. Couple notes:
* pulumi/actions-install-pulumi-cli is now called [pulumi/setup-pulumi](https://github.com/pulumi/setup-pulumi) and has been upgraded to the latest version, but the latest version unfortunately still runs Node 12. https://github.com/pulumi/setup-pulumi/issues/36 tracks addressing that.
* aws-actions/configure-aws-credentials also still runs on Node 12, so will continue to warn until https://github.com/aws-actions/configure-aws-credentials/issues/489 is addressed.
* The step that uses `set-output` appears to post a comment with a link back to the build job, presumably for …
=> Upgrade actions to address warnings

kubernetes-aws-csharp/Program.cs, kubernetes-aws-csharp/Pulumi.yaml, kubernetes-aws-go/Pulumi.yaml, kubernetes-aws-go/main.go, kubernetes-aws-python/Pulumi.yaml, kubernetes-aws-python/__main__.py, kubernetes-aws-typescript/Pulumi.yaml, kubernetes-aws-typescript/index.ts, kubernetes-aws-yaml/Pulumi.yaml, kubernetes-aws-yaml/Pulumi.yaml.append
This PR changes the default instance type for Kubernetes templates from t2 to t3 (t2 is not supported in all regions). Based on research using `aws ec2 describe-instance-type-offerings`, the t3 family appears to be supported in all (or very nearly all) regions and is a better option for a default value.
Fixes #501
=> Change default instance type

.github/workflows/cron.yml
In #500 and #506, we updated the tests to run against the local checkout. This change updates the daily CLI tests (which [have been failing in similar ways](https://github.com/pulumi/templates/actions/runs/3956441898/jobs/6775658807#step:21:1408)) to do the same.
=> Update daily CLI test to use local templates

aws-scala/Pulumi.yaml, aws-scala/build.sbt, aws-scala/src/main/scala/Main.scala
I have noticed that while [this blog post](https://www.pulumi.com/blog/announcing-infrastructure-as-code-with-java-and-pulumi/), and [this closed issue](https://github.com/pulumi/pulumi/issues/1539) exist,
in the blog it is stated: 
> Declare infrastructure using programs, classes, and libraries written in Java or other JVM languages (Kotlin, **Scala**, Clojure, Groovy, etc.).
however, `pulumi new` command doesn't have a scala template, specifically I was looking for the aws template,
I have found 2 resources regarding an example:
https://github.com/pulumi/pulumi-java/pull/791
https://blog.ediri.io/how-to-use-pulumi-and-scala-to-deploy-a-minecraft-server-on-a-digitalocean-droplet
with those examples, I was able to recreate the same 'default' aws bucket example,
and `pulumi up` works, …
=> Add scala template

generator/mod-templates/github-template.txt, github-go/go.mod, github-go/main.go
pulumi-github has been v5 since
https://github.com/pulumi/pulumi-github/releases/tag/v5.0.0
but `pulumi new` still generates v4 projects.
This upgrades the github-go template to the latest v5 release.
=> github-go: Use pulumi-github v5

container-aws-csharp/Program.cs, container-aws-go/go.mod, container-aws-go/main.go, container-aws-python/__main__.py, container-aws-typescript/index.ts, container-aws-yaml/Pulumi.yaml, container-aws-yaml/Pulumi.yaml.append
Adds the `forceDelete` option to `awsx.ecr.Repository` declarations to allow these resources to be destroyed along with the rest of the stack. (Currently, `pulumi destroy` fails on these templates.)
Fixes https://github.com/pulumi/templates/issues/525.
=> Force-delete repositories in container-aws templates

java/pom.xml
This commit pins `org.apache.maven.plugins:maven-compiler-plugin to 3.5.1` to resolve failing builds for UBI images on pulumi-docker-containers.
https://github.com/pulumi/pulumi-docker-containers/issues/127
pulumi-docker-containers has 2 different java builds.
- Debian (passing)
- UBI (failing)
UBI is failing running a test that runs the java pulumi/template with the following error message:
> Error: umi:pulumi:Stack test-env4268922448-p-it-ea7a4b0c6d-test-env42-4bd12ab9  [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.10.1:compile (default-compile) on project test-env4268922448: Fatal error compiling: error: release version 11 not supported -> [Help 1]
The Debian and UBI images differ on the version of `org.apache.maven.plugins:maven-compiler-plugin`
When …
=> Pin java template maven dependency to latest known good version.

azure-python/__main__.py, kubernetes-java/Pulumi.yaml, tests/internal/testutils/templates.go, tests/template_test.go
Adds support for applying `integration.ProgramTestOptions` on a template-by-template basis, primarily to allow us to test a subset of templates (e.g., our core starter templates) with full updates and diff checks.
Note that the checks in this PR are failing (e.g., [here](https://github.com/pulumi/templates/actions/runs/4380318017/jobs/7667248950#step:21:644)) -- this is expected until https://github.com/pulumi/pulumi-aws/issues/2403 is fixed and any necessary template dependencies in this repo are updated.  
Fixes #533.
=> Conditionally test some templates end to end

aiven-go/go.mod, alicloud-go/go.mod, auth0-go/go.mod, aws-go/go.mod, aws-native-go/go.mod, azure-classic-go/go.mod, azure-go/go.mod, civo-go/go.mod, digitalocean-go/go.mod, equinix-metal-go/go.mod, gcp-go/go.mod, go/go.mod, google-native-go/go.mod, kubernetes-go/go.mod, linode-go/go.mod, oci-go/go.mod, openstack-go/go.mod
Updates `go.mod`s to pull in latest fixes (most importantly https://github.com/pulumi/pulumi-aws/issues/2403).
=> Bump aws-go and others to pull in latest fixes

.github/workflows/performance_metrics_cron.yml
Trying out the version of the job here: https://github.com/pulumi/templates/actions/runs/4472575517
=> Use go 1.20x when running perf job

.github/workflows/ci.yml, .github/workflows/run-templates-command.yml
Fixes a bug that causes this to evaluate to `false` when the version is unset. (We want it to evaluate null/indefined instead.)
Fixes https://github.com/pulumi/templates/issues/548.
=> Fix template expression

static-website-aws-csharp/Program.cs, static-website-aws-go/main.go, static-website-aws-python/__main__.py, static-website-aws-typescript/index.ts, static-website-aws-yaml/Pulumi.yaml
This PR adjusts the AWS static website templates to account for new public ACL configurations by adding BucketOwnershipControls and BucketPublicAccessBlock resources
Fixes #558
=> Fix S3 public ACL configuration

kubernetes-azure-csharp/Program.cs, kubernetes-azure-csharp/Pulumi.yaml, kubernetes-azure-go/Pulumi.yaml, kubernetes-azure-go/main.go, kubernetes-azure-python/Pulumi.yaml, kubernetes-azure-python/__main__.py, kubernetes-azure-typescript/Pulumi.yaml, kubernetes-azure-typescript/index.ts
This PR updates the Kubernetes version to 1.26.3 (from 1.24.3) for all AKS templates (all `kubernetes-azure-*` templates).
This is a stopgap PR related to https://github.com/pulumi/templates/issues/562; I couldn’t quite get the final solution for that issue working as expected, so this PR at least updates the templates to a more recent version of Kubernetes.
=> Update AKS version for all Kubernetes-Azure templates

kubernetes-java/src/main/java/myproject/App.java
This now compiles, where as before it emitted:
```
Error:  [ERROR] COMPILATION ERROR :
Error:  [ERROR] /tmp/test-env1721584717/src/main/java/myproject/App.java:[46,35] cannot find symbol
symbol:   method orElseThrow()
location: variable m of type com.pulumi.kubernetes.meta.v1.outputs.ObjectMeta
Error:  [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project test-env1721584717: Compilation failure
Error:  [ERROR] /tmp/test-env1721584717/src/main/java/myproject/App.java:[46,35] cannot find symbol
Error:  [ERROR]   symbol:   method orElseThrow()
Error:  [ERROR]   location: variable m of type com.pulumi.kubernetes.meta.v1.outputs.ObjectMeta
Error:  [ERROR]
Error:  [ERROR] -> [Help 1]
Error:  [ERROR]
Error:  [ERROR] To see the full …
```
=> Fix kubernetes-java

aiven-typescript/package.json, random-typescript/package.json
There was a few projects that were not bumped to node 16. Not sure why, so though I'd bump 'em.
=> chore: bump to node 16

scaleway-go/go.mod
Should be 1.18 to align with our other templates.
=> Update the Go verson for Scaleway

.github/workflows/ci.yml, .github/workflows/cron.yml, .github/workflows/run-templates-command.yml
This repo's Windows tests have been failing for a while without emitting any log output. I figured this might have something to do with resource exhaustion, so I bumped the Windows runners to the same level we use to build the docs, and [that seems to have worked](https://github.com/pulumi/templates/actions/runs/5765561110), so this PR applies that setting for all of our Windows tests, and also adds macOS to the list where it had been excluded.
Fixes #607.
Fixes #556.
=> Increase the size of the Windows runners

sagemaker-aws-python/Pulumi.yaml
We currently only use this flag for our tier-1 templates (e.g., `aws-typescript` and the like). Removing it from this template will also "fix" the [failing tests](https://github.com/pulumi/templates/actions/runs/6127351193/job/16632983679) (i.e., by skipping them).
=> Unset the important flag on the SageMaker template

kubernetes-go/main.go
The template uses a method (`deployment.Metadata.Elem()`) which is apparently no longer valid.
Part of https://github.com/pulumi/pulumi-hugo/issues/3354.
=> Fix kubernetes-go template

serverless-aws-go/go.mod, serverless-aws-go/main.go
apigateway v1 and aws v6 are currently incompatible. The apigateway v2 release will be compatible with aws v6.
=> Revert serverless-aws-go with apigateway program to aws v5

linode-go/go.mod, linode-javascript/package.json, linode-python/requirements.txt, linode-typescript/package.json
Upgrade Linode templates to use the v4 package for all languages.
Issue was found by Linode when validating my contributed Pulumi guide:
https://github.com/linode/docs/pull/6555#issuecomment-1757067330
=> Upgrade to Linode v4 package

kubernetes-aws-csharp/Program.cs, kubernetes-aws-go/go.mod, kubernetes-aws-go/main.go, kubernetes-aws-python/__main__.py, kubernetes-aws-typescript/index.ts, kubernetes-aws-yaml/Pulumi.yaml
Update all Kubernetes on AWS (EKS) templates to use EKS >1.0 Update configuration values for private clusters for improved clarity
Fixes broken Go template
Closes #664
=> Update Kubernetes on AWS (EKS) templates

vm-azure-csharp/${PROJECT}.csproj, vm-azure-csharp/Program.cs, vm-azure-csharp/Pulumi.yaml, vm-azure-go/Pulumi.yaml, vm-azure-go/go.mod, vm-azure-go/main.go, vm-azure-python/Pulumi.yaml, vm-azure-python/__main__.py, vm-azure-python/requirements.txt, vm-azure-typescript/Pulumi.yaml, vm-azure-typescript/index.ts, vm-azure-typescript/package.json, vm-azure-yaml/Pulumi.yaml
This PR adds an SSH key to the "VM on Azure" architecture templates. Adding the SSH key enables automated testing of the templates, which are currently excluded from automated testing.
The PR includes the following changes:
* Updates templates to add an SSH key resource
* Uses the SSH key resource for the VM resource
* Removes the SSH key as a required configuration value
=> Add SSH key to enable testing

.github/workflows/run-templates-command.yml
Force an update of the Pulumi CLI to a min version of 3.95 as it adds support for new fields that have been added to templates.
The tests failing on this PR are related to our azure storage changing. I'm following up with that in a separate PR.
My [last PR](https://github.com/pulumi/templates/pull/697/) merged unexpectedly even with tests failing :/
=> [ci] force update of pulumi cli to > 3.95.0

aws-csharp/Program.cs, csharp/Program.cs
Fix two C# templates that were using three spaces instead of four. Verified all other C# templates are using four spaces.
Fixes #703.
=> Fix spacing in C# programs

container-gcp-csharp/Program.cs, container-gcp-go/main.go, container-gcp-python/__main__.py, container-gcp-typescript/index.ts
Update GCP cloudrun template to use docker image repo digest identifier
By using image name in the cloud run service, the image won't be redeployed when the app changes currently.
Ref:
https://github.com/pulumi/pulumi-gcp/issues/1166
https://github.com/pulumi/pulumi-docker/issues/726
https://github.com/pulumi/pulumi-docker/pull/739
=> Update GCP cloudrun template to use docker image repo digest identifier

.github/workflows/ci.yml, .github/workflows/cron.yml, .github/workflows/performance_metrics_cron.yml, .github/workflows/run-templates-command.yml
Similar to https://github.com/pulumi/examples/pull/1535, we would like to use the latest pulumi dev version here instead of just the latest version.
In fact in some places there was some (very outdated and no longer functional) code to attempt that.  Instead of the latest dev version it downloaded 3.40.0-alpha.1663101047 as of the time of this writing, which is less than ideal.  Always use the dev version here unless we explicitly request the "latest" version.
Fixes https://github.com/pulumi/pulumi/issues/10728
=> always use the latest pulumi dev version in CI

.github/workflows/cron.yml, .github/workflows/performance_metrics_cron.yml
The titles currently mention "Latest" pulumi CLI, however that's easily confused as the latest stable release, even though we are installing the dev versions now.
/cc @justinvp who noticed this
=> fix titles for installing the pulumi CLI

kubernetes-azure-csharp/Program.cs, kubernetes-azure-go/main.go, kubernetes-azure-python/__main__.py, kubernetes-azure-typescript/index.ts, kubernetes-azure-yaml/Pulumi.yaml
This PR does a couple of things:
1. It updates the default Kubernetes version to an LTS (long-term support) version that will be supported until mid-2025. This largely alleviates concerns about needing to regularly update the AKS templates as Azure adds and removes supported Kubernetes versions.
2. It addresses #563 by defining both a "user Kubeconfig" (which requires device code login and is suitable for per-user/interactive logins to the cluster) as well as an "admin Kubeconfig" (which uses certificate-based auth and is suitable for non-interactive logins/explicit providers). The admin Kubeconfig is exported as secret stack output for added security.
Fixes #563 
Fixes https://github.com/pulumi/pulumi-azure-native/issues/2399
=> Update AKS templates

.github/workflows/ci.yml, .github/workflows/cron.yml, .github/workflows/performance_metrics_cron.yml, .github/workflows/run-templates-command.yml
pulumi/pulumi generally supports the two latest Go releases.  Since 1.22.x came out, we dropped support for 1.20.x, and indeed compilation of the latest pulumi/pulumi source is failing with the latest Go version because of the missing `slices` package.
Update CI to the latest supported Go version, so we are able to update pulumi/pulumi in this repo.
(I need to update to the latest pulumi/pulumi to get dev SDKs tested, work for that is in https://github.com/pulumi/templates/pull/756.  But this feels separate enough to warrant a separate PR.)
We will also need to update the required CI jobs as the name changes based on the versions of the various toolchains.  I'm not an admin in this repo, so I can't do that myself unfortunately. (Or maybe we could make only the sentinel job required, since …
=> update Go version to 1.21.x

.github/workflows/ci.yml, .github/workflows/run-templates-command.yml
These tests seem to occasionally run out of disk space.  Free up some space before running them to avoid that.
=> free up disk space before tests

.github/workflows/cron.yml
We're already using the dev version for PRs and performance cron runs, but aren't currently for this cron workflow. Which means I generally have to look at recent PRs to see how dev builds are doing before publishing a new pulumi/pulumi release. This PR updates the cron workflow to use the dev release.
=> ci: Use the latest dev version for cron runs

azure-python/__main__.py, civo-python/__main__.py, civo-python/requirements.txt, container-aws-python/__main__.py
With type checking for dictionary literals, we now prefer this style over args classes https://github.com/pulumi/pulumi/issues/12689
=> Update more templates to used dictionary literals

container-azure-python/__main__.py, container-gcp-python/__main__.py
With type checking for dictionary literals, we now prefer this style over args classes https://github.com/pulumi/pulumi/issues/12689
=> Update more python templates to use dictionary literals

aws-csharp/Program.cs, aws-fsharp/Program.fs, aws-go/main.go, aws-java/src/main/java/myproject/App.java, aws-javascript/index.js, aws-python/__main__.py, aws-scala/src/main/scala/Main.scala, aws-typescript/index.ts, aws-visualbasic/Program.vb, aws-yaml/Pulumi.yaml, static-website-aws-csharp/Program.cs, static-website-aws-go/main.go, static-website-aws-python/__main__.py, static-website-aws-typescript/index.ts, static-website-aws-yaml/Pulumi.yaml
Adopting our own best-practice recommendation per https://github.com/pulumi/home/issues/3632
=> Update templates to use BucketV2

azure-classic-csharp/${PROJECT}.csproj, azure-classic-csharp/Pulumi.yaml, azure-classic-fsharp/${PROJECT}.fsproj, azure-classic-fsharp/Pulumi.yaml, azure-classic-go/Pulumi.yaml, azure-classic-go/go.mod, azure-classic-go/main.go, azure-classic-javascript/Pulumi.yaml, azure-classic-javascript/package.json, azure-classic-python/Pulumi.yaml, azure-classic-python/requirements.txt, azure-classic-typescript/Pulumi.yaml, azure-classic-typescript/package.json, azure-classic-visualbasic/${PROJECT}.vbproj, azure-classic-visualbasic/Pulumi.yaml, azure-classic-yaml/Pulumi.yaml
- Bump major version in dependencies.
- Add required subscriptionId config
Part of https://github.com/pulumi/pulumi-azure/issues/2336
=> Update Azure Classic to v6

README.md
Adds a few details to help with template-authoring guidance:
* Leave out unnecessary files
* Don't include lockfiles
* Apply sensible defaults for all config values
* Support minimum-supported runtimes
=> Add a few details to the README

kubernetes-gcp-yaml/Pulumi.yaml
The template currently contains a typo that results in the following error:
```
Diagnostics:
pulumi:pulumi:Stack (kubernetes-gcp-yaml-72f8d81-dev):
Error: error resolving type of resource gke-nodepool-sa: unable to find resource type "gcp:serviceAccount:Account" in resource provider "gcp"
on Pulumi.yaml line 79:
79:     type: gcp:serviceAccount:Account
```
Should be `serviceaccount`, not `serviceAccount`.
Fixes #793.
=> Fix typo in Kubernetes YAML architecture template

.github/workflows/test-templates.yml
There's an issue with this template causing it to fail when testing it. We're likely going to reduce the number of templates we support out of the box to only those that are most widely used, and likely ovh will be moved out (can be hosted elsewhere). Therefore, it's not worth spending a lot of time fixing up this template, so skip testing it for now.
=> Skip ovh-java test

static-website-aws-typescript/package.json
Per user reported bug, this version is stale and causes errors.
Testing this depends on: #844 so merge after that.
=> Upgrades stale version of synced-folder component

aws-java/pom.xml
We just released [v7.0.0-alpha.1](https://github.com/pulumi/pulumi-aws/releases/tag/v7.0.0-alpha.1) of the AWS provider. Our aws-java template sets a version range of `[6.68,7.0]` for the dependency, and so now we're pulling in the alpha. However there is an issue with this version as `BucketV2` seems to be gone (I don't think that's intentional). In any case, we don't want to use the alpha version here.
We need to update the version range in the template, but using `[6.68,7.0)` (note the `)`) does not do what you'd think [^1]. We need to set it to something like `[6.68,6.999]`.
We should check all of our other java templates for similar issues.
Fixes https://github.com/pulumi/pulumi-docker-containers/issues/494
[^1]: https://michakutz.medium.com/legit-but-useless-maven-version-ranges-expl …
=> [aws-java] Fix com.pulumi.aws version range
