pulumi/templates

kubernetes-typescript/Pulumi.yaml, kubernetes-typescript/index.ts
@joeduffy, here it is without the config and `"nginx"` inline.
=> Simplify the kubernetes template

kubernetes-javascript/.gitignore, kubernetes-javascript/Pulumi.yaml, kubernetes-javascript/index.js, kubernetes-javascript/package.json
Based on the TypeScript template.
Part of #34.
=> Add minimal Kubernetes JavaScript template

azure-go/main.go, azure-javascript/index.js, azure-python/__main__.py, azure-typescript/index.ts
The location is flowed automatically now.
=> No need to pass the location in Azure templates

kubernetes-typescript/index.ts
Take advantage of flow proxy support to simply
exported variable usage
=> Update k8s TS template

kubernetes-javascript/index.js
Take advantage of flow proxy support to simplify variable usage
=> Update k8s JS template

aws-fsharp/Program.fs, azure-fsharp/Program.fs, gcp-fsharp/Program.fs
Make F# templates a bit more lightweight
cc @chrsmith
=> Prettify F# templates

kubernetes-typescript/index.ts, kubernetes-typescript/package.json
=> Add kx to kubernetes-ts template

aws-csharp/Infra.csproj, aws-fsharp/Infra.fsproj, aws-visualbasic/Infra.vbproj, azure-csharp/Infra.csproj, azure-fsharp/Infra.fsproj, azure-visualbasic/Infra.vbproj, csharp/Infra.csproj, fsharp/Infra.fsproj, gcp-csharp/Infra.csproj, gcp-fsharp/Infra.fsproj, gcp-visualbasic/Infra.vbproj, visualbasic/Infra.vbproj
Update .NET references to the latest versions after the recent breaking changes
=> Bump .NET versions to latest

gcp-go/main.go
contributes to https://github.com/pulumi/docs/issues/2311
=> fix go gcp example

azure-fsharp/${PROJECT}.fsproj, azure-visualbasic/${PROJECT}.vbproj
Follow-up to https://github.com/pulumi/templates/pull/100.
=> Update F# and VB templates as well

alicloud-csharp/MyStack.cs, aws-csharp/MyStack.cs, azure-csharp/MyStack.cs, kubernetes-csharp/${PROJECT}.csproj, kubernetes-csharp/MyStack.cs, kubernetes-csharp/Program.cs, kubernetes-fsharp/${PROJECT}.fsproj
Together with #102, resolves #83
=> Update k8s .NET templates

gcp-csharp/Program.cs
I looked through the other C# and VB templates and didn't see anything else like this.
=> Fix gcp-csharp templated

kubernetes-go/main.go
missing some imports and assignment statements
=> fix go kubernetes template

alicloud-python/__main__.py, aws-python/__main__.py, azure-python/__main__.py, digitalocean-python/__main__.py, gcp-python/__main__.py, kubernetes-python/__main__.py, linode-python/__main__.py, openstack-python/__main__.py, packet-python/__main__.py, python/__main__.py
- C0114: Missing module docstring (missing-module-docstring)
- C0326: Exactly one space required after comma
And also made the string quotes consistent within each program.
Part of https://github.com/pulumi/pulumi/issues/3765
=> Fix pylint errors in Python templates

.github/workflows/ci.yml
=> Ensure we report test failures to slack

alicloud-go/go.mod, aws-go/go.mod, azure-go/go.mod, digitalocean-go/go.mod, gcp-go/go.mod, go/go.mod, kubernetes-go/go.mod, linode-go/go.mod, openstack-go/go.mod, packet-go/go.mod, packet-go/main.go
=> Bump the versions of go sdks

kubernetes-python/__main__.py
This can be tested out via:
```sh
pulumi new https://github.com/pulumi/templates/tree/justin/pyio/kubernetes-python
```
Fixes #120
=> Use input classes in Kubernetes Python template

azure-nextgen-csharp/MyStack.cs, azure-nextgen-go/go.mod, azure-nextgen-go/main.go, azure-nextgen-python/__main__.py, azure-nextgen-python/requirements.txt, azure-nextgen-typescript/index.ts, azure-nextgen-typescript/package.json
Update to `azure-nextgen` 0.2.0+ and adjust the code for the breaking change
=> Update to Azure NextGen v0.2.0

.github/workflows/ci.yml, Makefile
=> increase test timeout

azure-nextgen-fsharp/Program.fs
Fix https://github.com/pulumi/templates/issues/143
=> Fix Azure NextGen F# template

azure-javascript/.gitignore, azure-javascript/Pulumi.yaml, azure-javascript/index.js, azure-javascript/package.json
=> Revive the azure-javascript template

.github/workflows/cron.yml
=> Separating the cron job to ensure we test against latest + dev

.github/workflows/update-templates.yml, generator/generate-go-mod.sh
=> Adding the ability to trigger an update of the go.mod files

civo-go/Pulumi.yaml, civo-go/go.mod, civo-go/main.go
Signed-off-by: Engin Diri <engin.diri@mail.schwarz>
Hi good folks at Pulumi,
It would be nice to have a civo template to use in pulumi new
i start with the civo-go template.
=> Create civo-go template for pulumi new

aiven-go/Pulumi.yaml, aiven-go/go.mod, aiven-go/main.go
Signed-off-by: Engin Diri <engin.diri@mail.schwarz>
Hi nice folks at Pulumi,
It would be sweet to have a Aiven template to use in pulumi cli.
So I created this template.
=> Add aiven-go template to pulumi

github-go/Pulumi.yaml, github-go/go.mod, github-go/main.go, github-javascript/.gitignore, github-javascript/Pulumi.yaml, github-javascript/index.js, github-javascript/package.json, github-typescript/.gitignore, github-typescript/Pulumi.yaml, github-typescript/index.ts, github-typescript/package.json, github-typescript/tsconfig.json
add GitHub templates (golang, type- and javascript)
=> feat: add GitHub templates (golang, type- and javascript)

civo-go/go.mod, civo-go/main.go, civo-javascript/index.js, civo-javascript/package.json, civo-python/__main__.py, civo-python/requirements.txt, civo-typescript/index.ts, civo-typescript/package.json, templates.iml
chore: update civo version to 2.2.0 and fix breaking changes
=> chore: update civo version to 2.2.0 and fix breaking changes

aws-yaml/Pulumi.yaml.append, gcp-yaml/Pulumi.yaml
Fixes https://github.com/pulumi/docs/issues/7508.
=> Fix bucket resource name

.github/workflows/ci.yml
This is lame but apparently I missed one CI file in #302 - and the most important one
=> Switch CI workflow to .NET 6

alicloud-csharp/Program.cs, auth0-csharp/Program.cs, aws-csharp/Program.cs, aws-native-csharp/Program.cs, azure-classic-csharp/Program.cs, azure-csharp/Program.cs, csharp/Program.cs, gcp-csharp/Program.cs, github-csharp/Program.cs, google-native-csharp/Program.cs, kubernetes-csharp/Program.cs
Tactical fix for https://github.com/pulumi/pulumi/issues/10202
=> Fix csharp templates

alicloud-typescript/package.json, auth0-typescript/package.json, aws-native-typescript/package.json, aws-typescript/package.json, azure-classic-typescript/package.json, azure-typescript/package.json, civo-typescript/package.json, digitalocean-typescript/package.json, equinix-metal-typescript/package.json, gcp-typescript/package.json, github-typescript/package.json, google-native-typescript/package.json, kubernetes-typescript/package.json, linode-typescript/package.json, oci-typescript/package.json, openstack-typescript/package.json, typescript/package.json
=> Add main entry to all typescript templates

kubernetes-java/pom.xml, kubernetes-java/src/main/java/myproject/App.java
Update Kubernetes Java template imports after breaking changes in the kubernetes provider.
Part of https://github.com/pulumi/pulumi-java/issues/732
=> Update kubernetes-java after breaking changes

.github/workflows/performance_metrics_cron.yml, Makefile, tests/go.mod, tests/go.sum, tests/template_test.go, tests/testing_utils_test.go
On top of https://github.com/pulumi/pulumi-trace-tool/pull/2
Example run: https://github.com/pulumi/templates/actions/runs/2878948748
=> Fixing up trace collection for performance metrics

tests/template_test.go
It seems that our template tests run a redundant `yarn install` step. That is not what's happening for users typically, as `pulumi new` runs `npm install` and that brings the packages in. The change switches the tests to the more realistic scenario.
=> Do not yarn install

azure-fsharp/Program.fs
The csharp template makes this a secret, the fsharp template should to.
=> Fix azure-fsharp template to use CreateSecret

azure-java/src/main/java/myproject/App.java
Fixes [pulumi/templates#350](https://github.com/pulumi/templates/issues/350)
=> Fix azure-java template

.github/workflows/ci.yml, .github/workflows/cron.yml, .github/workflows/performance_metrics_cron.yml, .github/workflows/run-templates-command.yml
Fix https://github.com/pulumi/templates/issues/366
=> Fix ServiceAccount settings for GCP CI

.github/workflows/ci.yml, .github/workflows/cron.yml, .github/workflows/performance_metrics_cron.yml, .github/workflows/run-templates-command.yml
=> Run YAML tests

.github/workflows/ci.yml, .github/workflows/command_dispatch.yml, .github/workflows/cron.yml, .github/workflows/performance_metrics_cron.yml, .github/workflows/pr.yml, .github/workflows/run-templates-command.yml, .github/workflows/update-templates.yml
The checkout step on the performance cron was out of order, so the credentials were being overwritten during this process.
=> Fix Google Cloud auth step for CI

serverless-azure-csharp/Program.cs
I noticed yesterday that this template wasn't working because the ZIP file that gets created and uploaded to Azure didn't have the internal layout that Azure was expecting. (The archive produced by `Command.Local.Run` lets you filter the files that end up in the ZIP, but it doesn't expose a way to specify a root path for those files, so everything ends up prefixed by the path from which the Command was run, and it doesn't look like there's a way to configure this at the function-definition level, either.) So this change specifies an explicit build path (`publish`, which is also `.gitignore`d by default) and points a `FileArchive` resource at that path instead.
=> Fix serverless-azure-csharp template

.github/workflows/ci.yml, .github/workflows/cron.yml, .github/workflows/performance_metrics_cron.yml
Follow-up to #400. (I missed these additional references in that PR.)
=> Change remaining references to gotestfmt

kubernetes-gcp-csharp/${PROJECT}.csproj, kubernetes-gcp-csharp/Program.cs, kubernetes-gcp-csharp/Pulumi.yaml
This PR adds a C# template for standing up Kubernetes on Google Cloud.
=> Add C# template for Kubernetes on Google Cloud

azure-yaml/Pulumi.yaml, azure-yaml/Pulumi.yaml.append, kubernetes-azure-yaml/Pulumi.yaml, kubernetes-azure-yaml/Pulumi.yaml.append, oci-yaml/Pulumi.yaml, oci-yaml/Pulumi.yaml.append, serverless-aws-yaml/Pulumi.yaml, serverless-aws-yaml/Pulumi.yaml.append, serverless-azure-yaml/Pulumi.yaml, serverless-azure-yaml/Pulumi.yaml.append, serverless-gcp-yaml/Pulumi.yaml, serverless-gcp-yaml/Pulumi.yaml.append, static-website-azure-yaml/Pulumi.yaml, static-website-azure-yaml/Pulumi.yaml.append
=> Fix YAML warnings

metadata/architectures.yaml, metadata/dist/metadata.json, metadata/groups/helm-kubernetes.yaml, metadata/groups/serverless-application-azure.yaml, metadata/groups/serverless-application-gcp.yaml, metadata/groups/virtual-machine-aws.yaml, metadata/groups/webapp-kubernetes.yaml
Filling out the metadata for the templates that went in yesterday (and a few that were overlooked).
=> Add template metadata

.github/workflows/add-to-project.yml
Adds a workflow file to add new issues to the Developer Relations board for triage.
=> Add a workflow file for handling new issues

azure-classic-csharp/${PROJECT}.csproj, azure-classic-fsharp/${PROJECT}.fsproj, azure-classic-go/go.mod, azure-classic-javascript/package.json, azure-classic-python/requirements.txt, azure-classic-typescript/package.json, azure-classic-visualbasic/${PROJECT}.vbproj
Now using latest version of azure classic packages
=> Updated the azure classic templates

kubernetes-gcp-yaml/Pulumi.yaml, metadata/dist/metadata.json
Fixes https://github.com/pulumi/templates/issues/448.
=> Fix Kubernetes template description

aiven-typescript/.gitignore, aiven-typescript/Pulumi.yaml, aiven-typescript/index.ts, aiven-typescript/package.json, aiven-typescript/tsconfig.json
This PR adds a TypeScript template for Aiven. Currently, there is one Aiven template available for Go.
A related PR is also open which adds a Python template for Aiven: https://github.com/pulumi/templates/pull/479
=> Aiven TypeScript template.

civo-go/go.mod, civo-javascript/package.json, civo-python/requirements.txt, civo-typescript/package.json
=> feat: update civo templates

container-azure-csharp/${PROJECT}.csproj, container-azure-csharp/Program.cs, container-azure-go/go.mod, container-azure-go/main.go, container-azure-python/__main__.py, container-azure-python/requirements.txt, container-azure-typescript/index.ts, container-azure-typescript/package.json, container-gcp-csharp/${PROJECT}.csproj, container-gcp-csharp/Program.cs, container-gcp-go/go.mod, container-gcp-go/main.go, container-gcp-python/__main__.py, container-gcp-python/requirements.txt, container-gcp-typescript/index.ts, container-gcp-typescript/package.json
Addresses https://github.com/pulumi/templates/issues/567
Update templates to use docker v4 and set standard platform.
=> Update templates to docker v4

azure-csharp/${PROJECT}.csproj, azure-fsharp/${PROJECT}.fsproj, azure-go/go.mod, azure-go/main.go, azure-java/pom.xml, azure-javascript/package.json, azure-python/requirements.txt, azure-typescript/index.ts, azure-typescript/package.json, container-azure-csharp/${PROJECT}.csproj, container-azure-go/go.mod, container-azure-go/main.go, container-azure-python/requirements.txt, container-azure-typescript/package.json, generator/mod-templates/azure-template.txt, kubernetes-azure-csharp/${PROJECT}.csproj, kubernetes-azure-go/go.mod, kubernetes-azure-go/main.go, kubernetes-azure-python/requirements.txt, kubernetes-azure-typescript/package.json, serverless-azure-csharp/${PROJECT}.csproj, serverless-azure-go/go.mod, serverless-azure-go/main.go, serverless-azure-python/requirements.txt, serverless-azure-typescript/package.json, static-website-azure-go/go.mod, static-website-azure-go/main.go, vm-azure-go/go.mod, vm-azure-go/main.go
=> Set azure native provider version to v2

azure-javascript/package.json, azure-python/requirements.txt, azure-typescript/package.json, container-azure-go/go.mod, container-azure-python/requirements.txt, kubernetes-azure-go/go.mod, serverless-azure-go/go.mod, static-website-azure-csharp/${PROJECT}.csproj, static-website-azure-go/go.mod, static-website-azure-python/requirements.txt, static-website-azure-typescript/package.json, vm-azure-csharp/${PROJECT}.csproj, vm-azure-go/go.mod, vm-azure-python/requirements.txt, vm-azure-typescript/package.json
From @iwahbe feedback here: https://github.com/pulumi/templates/pull/587#pullrequestreview-1530246962
=> Adjust azure-native version deps per feedback

container-aws-typescript/index.ts
Add required name arg for fargate template
=> Add required name arg for fargate template

container-aws-csharp/Program.cs, container-aws-go/main.go, container-aws-python/__main__.py, container-aws-typescript/index.ts, container-aws-yaml/Pulumi.yaml
=> Add required properties to container-aws-* templates

openstack-go/main.go, openstack-javascript/index.js, openstack-python/__main__.py, openstack-typescript/index.ts, openstack-yaml/Pulumi.yaml
Hello, 
I updated the Ubuntu version to the latest LTS for OpenStack templates. 😊
=> Update Ubuntu version for OpenStack templates

kubernetes-aws-python/requirements.txt
=> Unpin alpha version of pulumi-eks python template

.github/workflows/ci.yml
This should fix the error seen in https://github.com/pulumi/templates/actions/runs/8116393836
=> specify pulumi version correctly

container-aws-typescript/tsconfig.json, helm-kubernetes-typescript/tsconfig.json, kubernetes-aws-typescript/tsconfig.json, serverless-aws-typescript/tsconfig.json, serverless-azure-typescript/tsconfig.json
Follow up from https://github.com/pulumi/templates/pull/774
=> Use spaces instead of tabs in tsconfig.json

.github/workflows/test-metadata.yml, .github/workflows/test-templates.yml
Makes the names of the templates and metadata workflows a little clearer.
=> Adjust workflow names for clarity

.github/workflows/test-templates.yml, vm-gcp-python/__main__.py
With type checking for dictionary literals, we now prefer this style over args classes https://github.com/pulumi/pulumi/issues/12689
=> Update vm-gcp-python to used dictionary literals

github-go/main.go, github-javascript/index.js, github-python/__main__.py, github-typescript/index.ts, github-yaml/Pulumi.yaml
Fixes [#842](https://github.com/pulumi/templates/issues/842)
=> Converge all language examples for Github template to use the same output name.

generator/generate-go-mod.sh
Fixes failing automation referenced here: [#838](https://github.com/pulumi/templates/issues/838)
=> Remove aws-native from providers list

aws-java/pom.xml, azure-java/pom.xml, gcp-java/pom.xml, java-gradle/app/build.gradle, java-jbang/src/main.java, java/pom.xml, kubernetes-java/pom.xml, kubernetes-ovh-java/pom.xml, oci-java/pom.xml, oci-java/src/main/java/myproject/App.java, ovh-java/pom.xml, random-java/pom.xml
We've shipped v1.3.0 of the core SDK and there are more recent provider SDKs.
Fixes #881
=> Update Java template dependencies

esc-connector-lambda-typescript/Pulumi.yaml, esc-connector-lambda-typescript/README.md, esc-connector-lambda-typescript/index.ts
- Adding description to the template
- Updating wording on OIDC provider exists error
- Updating `managingCredentials` environment to use secret for password
- Fixes https://github.com/pulumi/pulumi-service/issues/27810v
- Manually deployed
=> Updating esc-connector template

aws-csharp/README.md, aws-go/README.md, aws-java/README.md, aws-python/README.md, aws-typescript/README.md, aws-yaml/README.md, azure-csharp/README.md, azure-go/README.md, azure-java/README.md, azure-python/README.md, azure-typescript/README.md, azure-yaml/README.md, gcp-csharp/README.md, gcp-go/README.md, gcp-java/README.md, gcp-python/README.md, gcp-typescript/README.md, gcp-yaml/README.md
Generated with
```sh
#!/bin/bash
ORIGINAL_DIR=$(pwd)
echo "Starting to process cloud provider directories..."
for dir in */; do
dir=${dir%/}
if [[ "$dir" == azure-classic* || "$dir" == azuredevops* || "$dir" == google-native* ]]; then
echo "Skipping excluded directory: $dir"
continue
fi
if [[ "$dir" == aws* || "$dir" == azure* || "$dir" == google* || "$dir" == gcp* ]]; then
if [ -f "$dir/README.md" ]; then
echo "Skipping $dir (README.md already exists)"
continue
fi
echo "Processing template: $dir"
cd "$dir"
codex -q "$(cat ../prompt.md)" --auto-edit > /dev/null 2>&1
cd "$ORIGINAL_DIR"
echo "Finished processing: $dir"
echo "------------------------"
fi
done
echo "All matching cloud directories processed."
```
`prompt.md`:
```md
Generate a rich, project-specific `README.md` file for the …
```
=> Add README files to major templates

.github/CODEOWNERS
Don't make me manually pick a reviewer on PRs please!
=> Add platform team as owner

hello-aws-javascript/index.js
Removing a 404 page from the template.
=> [hello-aws-javascript] Update index.js link to @pulumi/aws docs
